### ISSUE TITLE
Can not install this library on Fedora 20

### ISSUE THREAD

**Issue by rickhau** [sahlberg/libnfs-python#1]
Hi, sahlberg

   I used the following steps to install this python library but failed the installation. Would you mind shedding me some light on this? Any advice is highly appreciated.

1) $ git clone https://github.com/sahlberg/libnfs-python.git
2) $ cd libnfs-python
3) $ sudo python setup.py install

Then, it comes to the following error. 

Error message:
libnfs/libnfs_wrap.c:2969:25: fatal error: nfsc/libnfs.h: No such file or directory
 #include <nfsc/libnfs.h>
                         ^
compilation terminated.
error: command 'gcc' failed with exit status 1
[fitbranded@localhost libnfs-python]$ 

  It seems to require nfsc/libnfs.h to proceed the compilation. 
  If I made any step wrong, please let me know.

Thank you.

**Comment by sahlberg** [comment]
Hi,

You need to have the libnfs library installed and its header files.
https://github.com/sahlberg/libnfs

libnfs and libnfs-dev   should be available on most distros, so you should
be able to install it via yum.
I don;t know the exact name of the package on Fedora though.


Otherwise you could also just install libnfs from sources from
https://github.com/sahlberg/libnfs
Make sure you run configure as :
./configure --prefix=/usr when building so that it will install the library
and headers in the right place.

**Comment by rickhau** [comment]
Hi, sahlberg

   Many thanks for your swift response.  I also can not find the libnfs and libnfs-devel packages using yum tool. Then, I tried to build the libnfs but it seems not easy to compile the environment.

$ git clone https://github.com/sahlberg/libnfs.git
$ ./configure
bash: ./configure: No such file or directory

  Even I used `autoconf` or `autoreconf` to generate the configure file but I still ran into the failure.

$ ./configure
./configure: line 2100: syntax error near unexpected token `-Wall'
./configure: line 2100: `AM_INIT_AUTOMAKE(-Wall foreign)'
$ 

  Do you have any suggestions? 
  Thanks.

**Comment by sahlberg** [comment]
On Wed, Apr 22, 2015 at 8:37 AM, Rick <notifications@github.com> wrote:

> Hi, sahlberg
>
> Many thanks for your swift response. I also can not find the libnfs and
> libnfs-devel packages using yum tool. Then, I tried to build the libnfs but
> it seems not easy to compile the environment.
>
> $ git clone https://github.com/sahlberg/libnfs.git
> $ ./configure
> bash: ./configure: No such file or directory
>

Libnfs does not ship with a configure script. You need to generate one by
running the ./bootstrap script.
But you probably should not since Fedora does provide both libnfs and
libnfs-devel already.

QEMU and KODI/XBMC all depend on  libnfs so these packages are available
through the normal yum repositories.
I do not know the exact name that the Fedora folks use for this package
though.
I think it might be libnfs4 or similar.

 Check those packages, they might indicate what the correct name for libnfs
on Fedora is.


Even I used autoconf or autoreconf to generate the configure file but I

**Comment by sahlberg** [comment]
This page describes how to compile Kodi for Fedora and contains a
description how they compile libnfs during their build :

http://kodi.wiki/view/HOW-TO:Compile_Kodi_for_Linux_on_Fedora_Red_Hat_Enterprise_Linux_CentOS

**Comment by rickhau** [comment]
Thanks, sahlberg.

I can succeed to compile the libnfs library and libnfs-python now.

```
$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing libnfs.egg-info/PKG-INFO
writing top-level names to libnfs.egg-info/top_level.txt
writing dependency_links to libnfs.egg-info/dependency_links.txt
reading manifest file 'libnfs.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'libnfs.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/libnfs
copying build/lib.linux-x86_64-2.7/libnfs/__init__.py -> build/bdist.linux-x86_64/egg/libnfs
copying build/lib.linux-x86_64-2.7/libnfs/_libnfs.so -> build/bdist.linux-x86_64/egg/libnfs
copying build/lib.linux-x86_64-2.7/libnfs/libnfs.py -> build/bdist.linux-x86_64/egg/libnfs
byte-compiling build/bdist.linux-x86_64/egg/libnfs/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/libnfs/libnfs.py to libnfs.pyc
creating stub loader for libnfs/_libnfs.so
byte-compiling build/bdist.linux-x86_64/egg/libnfs/_libnfs.py to _libnfs.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying libnfs.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying libnfs.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying libnfs.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying libnfs.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
libnfs.libnfs: module references __file__
creating 'dist/libnfs-1.0_1-py2.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing libnfs-1.0_1-py2.7-linux-x86_64.egg
removing '/usr/lib64/python2.7/site-packages/libnfs-1.0_1-py2.7-linux-x86_64.egg' (and everything under it)
creating /usr/lib64/python2.7/site-packages/libnfs-1.0_1-py2.7-linux-x86_64.egg
Extracting libnfs-1.0_1-py2.7-linux-x86_64.egg to /usr/lib64/python2.7/site-packages
libnfs 1.0-1 is already the active version in easy-install.pth

Installed /usr/lib64/python2.7/site-packages/libnfs-1.0_1-py2.7-linux-x86_64.egg
Processing dependencies for libnfs==1.0-1
Finished processing dependencies for libnfs==1.0-1
$ 
```

However, when I want to try the sample code in the README file. It pops up the following error message. 

```
Python 2.7.5 (default, Nov  3 2014, 14:26:24) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libnfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "libnfs/__init__.py", line 17, in <module>
    from libnfs import *
  File "libnfs/libnfs.py", line 28, in <module>
    _libnfs = swig_import_helper()
  File "libnfs/libnfs.py", line 24, in swig_import_helper
    _mod = imp.load_module('_libnfs', fp, pathname, description)
ImportError: libnfs/_libnfs.so: undefined symbol: nfs_stat64
>>> 
```

Do you have any suggestions? 
Many thanks for your help.

**Comment by sahlberg** [comment]
ok   progress.

I can take a look sometime tomorrow.

**Comment by rickhau** [comment]
Thank you, sahlberg.

**Comment by sahlberg** [comment]
ImportError: libnfs/_libnfs.so: undefined symbol: nfs_stat64


Older versions of libnfs did not have the nfs_stat64 symbolt.

It seems like you have an old version of libnfs installed that is
lacking this new function.


Can you check that you do not have any old versions of the libnfs
share dlibrary installed and ONLY have the

one that you installed with :

./configure --prefix=/usr


cd .

sudo find . | grep libnfs


should show you what files are installed.

**Comment by sahlberg** [comment]
I have tested with Fedora21.

First install libnfs.  Configure it with   ./configure --prefix=/usr

Then install libnfs-python


This worked for me.
However, make sure you don't already have an old version of libnfs
installed.
The symbol nfs_stat64 was added in version 1.9.2 that was release only a
year ago,
so it is possible that your distro shipped an older version of the library
and libnfs-python used that version instead.

**Comment by rickhau** [comment]
Thanks, sahlberg. Yes, I had old libnfs-1.3.0 installed on my Fedora 20.

I removed my old libnfs-1.3.0 and re-install libnfs-1.9.7.tar.gz.
I ran into the following error.
```
Python 2.7.5 (default, Nov  3 2014, 14:26:24)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libnfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "libnfs.py", line 28, in <module>
    _libnfs = swig_import_helper()
  File "libnfs.py", line 20, in swig_import_helper
    import _libnfs
ImportError: No module named _libnfs
```
Then, I compile the libnfs folder and re-run again. 
It works now!!! :)

It seems that `sudo python setup.py install` did not make the modules under libnfs folder causing this error. I am not sure if you have the same issue.

Anyway, thanks and I enjoy this module now!!! 
Your help is highly appreciated!!

**Comment by sahlberg** [comment]
Hi Rick,

Good to hear it works now for you.
The module is still a bit incomplete, it does not for example provide any
way to easily scan directories etc,  but it works for basic file i/o.

It was mainly done to see if there was any interest in pyfilesystem to add
NFS support to their nice wrappers. But there was not much interest :-(


I can not promise to be able to add much new features to libnfs-python but
feel free to ask.
Or even better, send pull requests if you add new cool or useful things to
it.

regards
ronnie sahlberg

**Comment by anian2005** [comment]
pip install libnfs fails on mac with the below error 


gcc -fno-strict-aliasing -I/anaconda2/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/include/python2.7 -c libnfs/libnfs_wrap.c -o build/temp.macosx-10.6-x86_64-2.7/libnfs/libnfs_wrap.o
    libnfs/libnfs_wrap.c:2969:10: fatal error: 'nfsc/libnfs.h' file not found
    #include <nfsc/libnfs.h>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-pKcqdD/libnfs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-OYInwq/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-pKcqdD/libnfs/
