### ISSUE TITLE
cannot generate libnfs_wrap.c

### ISSUE THREAD

**Issue by sanjosh** [sahlberg/libnfs-python#15]
Sorry to bother you but I am a newbie in swig and can't figure this out.

I am running ubuntu 14.04.  I already installed libnfs, swig and pcre (apt-get install pcregrep libnfs-dev swig) but it seems the libnfs_wrap.c is not getting generated

Running setup.py does not seem to generate the same output as seen here 
http://rickhau.github.io/blog/2015/05/08/install-libnfs-python-library/

swig is installed in /usr/local/bin, so is pcre-config

Is something missing in my setup ?

$ sudo python setup.py install

> running install
> running build
> running build_py
> creating build
> creating build/lib.linux-x86_64-2.7
> creating build/lib.linux-x86_64-2.7/libnfs
> copying libnfs/__init__.py -> build/lib.linux-x86_64-2.7/libnfs
> running build_ext
> building 'libnfs._libnfs' extension
> creating build/temp.linux-x86_64-2.7
> creating build/temp.linux-x86_64-2.7/libnfs
> x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c libnfs/libnfs_wrap.c -o build/temp.linux-x86_64-2.7/libnfs/libnfs_wrap.o
> x86_64-linux-gnu-gcc: error: libnfs/libnfs_wrap.c: No such file or directory
> x86_64-linux-gnu-gcc: fatal error: no input files
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

$ ls -lR build/

> build/:
> total 8
> drwxr-xr-x 3 root root 4096 Dec  2 09:32 lib.linux-x86_64-2.7
> drwxr-xr-x 3 root root 4096 Dec  2 09:32 temp.linux-x86_64-2.7
> 
> build/lib.linux-x86_64-2.7:
> total 4  
> drwxr-xr-x 2 root root 4096 Dec  2 09:32 libnfs
> 
> build/lib.linux-x86_64-2.7/libnfs:
> total 8
> -rw-r--r-- 1 root root 7649 Dec  2 09:02 __init__.py
> 
> build/temp.linux-x86_64-2.7:
> total 4
> drwxr-xr-x 2 root root 4096 Dec  2 09:32 libnfs
> 
> build/temp.linux-x86_64-2.7/libnfs:
> total 0
>

**Comment by sahlberg** [comment]
Hi,

Ubuntu ships really old versions of libnfs which lacks some symbols that
the python bindings need.

Please try to remove libnfs and the devel package using apt-get and instead
build and install libnfs from sources.

**Comment by sanjosh** [comment]
I did build libnfs, swig and pcre from source but that didn't solve the problem.

Is there some debug or verbose flag I can enable to find out why swig isn't generating the libnfs_wrap.c ?

**Comment by sahlberg** [comment]
On Fri, Dec 2, 2016 at 6:53 AM, sanjosh <notifications@github.com> wrote:

> I did build libnfs, swig and pcre from source but that didn't solve the
> problem.
>
> Is there some debug or verbose flag I can enable to find out why swig
> isn't generating the libnfs_wrap.c ?
>

I don't know much about swig or python building modules. :-(
Building the module on newer versions of ubuntu works though.

I can try setting up a 14.04 VM and see if I can get it to build.

**Comment by karasu** [comment]
Solved! Before running setup.py, make must be run inside the libnfs folder:

```
cd libnfs-python/libnfs
make
```

Cheers!

**Comment by sahlberg** [comment]
Thanks. INSTALL has been updated.
