### ISSUE TITLE
Support struct timeval parameters to nfs_utimes() and nfs_lutimes()

### ISSUE THREAD

**Issue by earlchew** [sahlberg/libnfs-python#25]
As a Python developer, I want to use nfs_utimes() and nfs_lutimes(), so that I can set file modification times.

The current implementation does not provide a way to configure the pair of timeval parameters to `nfs_times()` or `nfs_utimes()`.

Using SWIG `carrays.i` allows the following:
```
tv1 = libnfs.timeval()
tv1.tv_sec = 1
tv1.tv_usec = 2

tv2 = libnfs.timeval()
tv2.tv_sec = 3
tv2.tv_usec = 4

tva = libnfs.new_TimeValArray(2)
libnfs.TimeValArray_setitem(tva, 0, tv1)
libnfs.TimeValArray_setitem(tva, 1, tv2)

libnfs.nfs_utimes(None, None, tva)
```

**Comment by sahlberg** [comment]
Merged. Thanks.
