### ISSUE TITLE
ImportError: libnfs.so.13: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wantao666** [sahlberg/libnfs-python#41]
i had finished install `https://github.com/sahlberg/libnfs`
and `pip install libnfs` successfully.

but when i use this module by `import libnfs`,it's wrong .
the error is `ImportError: libnfs.so.13: cannot open shared object file: No such file or directory`

i dont't know how to resolve this issue,hope reply soon.

**Comment by sahlberg** [comment]
On Mon, Oct 26, 2020 at 1:12 PM Selenium <notifications@github.com> wrote:
>
> i had finished install https://github.com/sahlberg/libnfs
> and pip install libnfs successfully.
>
> but when i use this module by import libnfs,it's wrong .
> the error is ImportError: libnfs.so.13: cannot open shared object file: No such file or directory
>
> i dont't know how to resolve this issue,hope reply soon.


My python and pip skills are very weak.
This does sound like you built it successfully but it will not run
applications that use it.
This sounds like that the search path for shared libraries that your
python interpreter uses
does not include the path to the directory where libnfs.so.13 is installed.

Check where libnfs.so.13 is installed and then check that the python
environment is set up to load shared
libraries from that location.

This could possibly point towards a solution:
https://stackoverflow.com/questions/1099981/why-cant-python-find-shared-objects-that-are-in-directories-in-sys-path


regards
ronnie sahlberg

**Comment by wantao666** [comment]
yeah,the problem is libnfs don't find the libnfs.so.13,by setting **export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"** in /etc/profile can resolve this problem

https://blog.csdn.net/qq_45453266/article/details/110478540

**Comment by jony89** [comment]
Also, debian slim-buster does not have this shared object. need to upgrade to bullseye
