### ISSUE TITLE
Unable to open in Ubuntu 14.04

### ISSUE THREAD

**Issue by Abondened** [sahlberg/libnfs-python#8]
This error shows every time I'm trying to open file using nfs.open(args) 
![libnfs](https://cloud.githubusercontent.com/assets/14872377/12294511/0efad072-ba21-11e5-9a29-345087214510.jpg)

Thank You

**Comment by sahlberg** [comment]
This command works for me:
PYTHONPATH=libnfs-python/build/lib.linux-x86_64-2.7 python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libnfs
>>> nfs = libnfs.NFS('nfs://127.0.0.1/data/tmp')
>>> a = nfs.open('/foo-test', mode='w+')
>>> 

Looks like you are getting EIO from the server. That could be a configuration issue for your NFS server.
I assume you have set up to export /data/tmp in your /etc/exports file and you have started the nfs server ?


Try to collect a wireshark trace of the traffic. It might tell why you can not access the share.

**Comment by Abondened** [comment]
Still I'm getting same error.

**Comment by sahlberg** [comment]
Ok, you need to provide some data then.


1, Run this command and make sure it works :
nfs-ls nfs://127.0.0.1/data/tmp

That should successfully list the content of the directory.

2,
Collect a network trace on loopback, for example using wireshark, and I can
take a look at it to see what is happening.
Collect the network trace while you are issuing the python commands.

**Comment by sahlberg** [comment]
No further data to debug with.
